sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: dg89RV4A6Qjst9JT5Kz93sikAbB1o4uKZshcHnO+vCIlMbCymUhm0wlqovp0z4ZXdwPpa65szv85UZ3YS3at0T7dlg53FGebre1b/GJmOvFiMY1+8qirccR1oC4g1LjN4ybmL7GqxJyy8sjCDKiu1UiEPkjRpFewLZ9Hmv8y/9BKPjRzbfPaSQS5Xty31cilhjAjcy600RWu+3N4QMdFScdNePC8uTYjSJ/vc2RgVv24JxEdYxDSu5lNp/uVnfG5b67Pa2gywIRZFf1V0z9n0FVHyRSFwz5VOgJxb/U+lyXsgeEOIPGvtGBXJDE+b3XtZ9xZrEaLiC7CBX8PL+b3PhEuOE5J9LuGpM+xXsb5DTjYFp+QjM5UP35igZNDPQjzIVnayA8cMSJHYiwvf5hyE3D92spitF9MVyQEicZIg+nqaADjML3yNqahhy0xjkZiBeeSWctt0NgmAWw2acRD8Y5N5zLh+IRwGeRBTG0Wr1aJ6yiOoqbD2lj9uPskIv4BVrKKBMzpOu8N568rN0snP7yLkICtFHAhaiXHs4erItDZqj0tB88k7ilwE/2wFI6TyJzutiMFpyNNeROoGNtv5S/S1UnCEcjvQATcU00TX7kwHt8rKA5IGERiTisJdscPW027Le1USUu3XWPcu9psbXHI15HTs4Cl9Pj2s525nNU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-House-of-the-Wolfings--13-A-Tale-of-the-House-of-the-Wolfings-and-All-the-Kindreds-of-the-__2885
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy